openapi: 3.0.0
info:
  title: 'API Documentation - RevoU Milestone Project Week 11'
  version: '1.0'
  description: 'Back-end API for reviewing movies from user to other user. Middleware, authentication, and authorization assignment.'
servers:
  - url: http://localhost:2020/ 
    description: 'Deployment Server'
  - url: https://weak-blue-cow-hose.cyclic.app/ 
    description: 'Deployment Server 2'
paths:
  /:
    get:
      summary: Homepage
      responses:
        '200':
          description: Welcome to the homepage
  /user/register:
    post:
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
                - username
                - password
                - role
      responses:
        '200':
          description: Successful response
  /user/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: User logged in successfully
  /user/allusers:
    get:
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all users
  /review:
    get:
      summary: Get all reviews
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of all reviews
    post:
      summary: Create a review
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                genre:
                  type: string
                director:
                  type: string
                rating:
                  type: string
                review:
                  type: string
              required:
                - title
                - genre
                - director
                - rating
                - review
      responses:
        '200':
          description: Review created successfully
  /review/{reviewId}:
    put:
      summary: Update all review by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                genre:
                  type: string
                director:
                  type: string
                rating:
                  type: string
                review:
                  type: string
              required:
                - title
                - genre
                - director
                - rating
                - review
      responses:
        '200':
          description: Review updated successfully
    patch:
      summary: Update review status by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
              required:
                - status
      responses:
        '200':
          description: Review status updated successfully
    delete:
      summary: Delete a review by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Review deleted successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
